accounts/urls.py
from django.conf.urls.defaults import patterns, url
from accounts.forms import LoginForm
from django.contrib.auth import views as auth_views

urlpatterns = patterns('accounts.views',
    url(r'^login/$', auth_views.login, {'template_name': 'accounts/login.html', 'authentication_form':LoginForm }, name = 'login'),
    url(r'^register/$', 'register', name = 'register'),
    url(r'^profile/(?P<username>\w+)/$', 'profile', name='profile'),
    url(r'^settings/(?P<item>\w+)/$', 'settings', name='settings'),
    url(r'^reset/$', 'reset_psw', name='reset_psw'),
    url(r'^reset/confirm/(?P<tmp_psw>\w+)/$', 'reset_psw_confirm', name = 'reset_psw_confirm'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'home.html', 'next_page': '/login/'}, name='logout'),
    url(r'^users/$', 'list_user', name='users'),
    url(r'^list_follow_user/$', 'list_follow_user', name='list_follow_user'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin

from notification import urls as notification

import settings
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'views.home', name='home'),
    url(r'^', include('tools.urls')),
    url(r'^', include('accounts.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^unread$', 'views.unread', name='unread'),
    url(r'^works/', include('works.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^notification/', include(notification)),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
)

accounts/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from easy_thumbnails.fields import ThumbnailerImageField
from notification import models as notification
from works.models import Work


class UserProfile(models.Model):
    user = models.ForeignKey(User, related_name='profile')
    avatar = ThumbnailerImageField(upload_to='avatar', default='avatar/default_avatar.jpg', resize_source=dict(size=(200, 250), crop='big'),)
    website = models.URLField(blank = True)
    intro = models.TextField()
    location = models.CharField(max_length = 50, blank = True)
    true_name = models.CharField(max_length = 14, blank = True)
    #email = models.EmailField()

class Visitor(models.Model):
    user = models.ForeignKey(User, related_name='visite')
    profile = models.ForeignKey(UserProfile, related_name='popularity')
    datetime = models.DateTimeField(auto_now_add = True)
    comment = models.CharField(max_length = 20, blank = True)

    class Meta:
        ordering = ['-datetime']
    
def create_user_profile(sender = None, instance = None, created = False, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
        Skill.objects.create(user=instance, skill='word')
        Skill.objects.create(user=instance, skill='image')
        Skill.objects.create(user=instance, skill='other')
        
models.signals.post_save.connect(create_user_profile, sender = User)

SKILL_CHOICES = (
    ('word', u'写手'),
    ('image', u'画师'),
#    ('design', u'设计美工'),
#    ('prog', u'程序员'),
#    ('music', u'音乐制作'),
#    ('onlook',u'围观'),
    ('other', u'其他'),
)
SKILL_CHOICES_MAP = {
    'word': u'写手',
    'image': u'画师',
    'other': u'其他',
}
class Skill(models.Model):
    user = models.ForeignKey(User, related_name='skills')
    skill = models.CharField(max_length=8, choices=SKILL_CHOICES)
    exp = models.IntegerField(default = 0)
    today_exp = models.IntegerField(default = 0)

class AccountTempPassword(models.Model):
    user = models.ForeignKey(User, related_name='tmp_psw')
    tmp_psw = models.CharField(max_length = 20)
    datetime = models.DateTimeField(auto_now_add = True)

class Invitation(models.Model):
    INVITE_CHOICES = (
        (u'noanswer', u'未响应'),
        (u'accept', u'已接受'),
        (u'reject', u'已拒绝')
    )
    work = models.ForeignKey(Work, related_name='invitation')
    invited = models.ForeignKey(User, related_name='invited')
    role = models.CharField(max_length=8, choices=SKILL_CHOICES)
    reason = models.CharField(max_length = 300)
    invite_status = models.CharField(max_length=8, choices=INVITE_CHOICES)
    notice = models.ForeignKey(notification.Notice, default=0)

accounts/forms.py
#coding=utf-8

from django import forms
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.forms.util import ErrorList

#from apps.accounts.models import AccountTempPassword

class LoginForm(AuthenticationForm):
    username = forms.CharField(error_messages = {'required': u'用户名或邮箱不能为空'}, max_length = 30)
    password = forms.CharField(widget=forms.PasswordInput, error_messages = {'required': u'密码不能为空'})

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username and password:
            self.user_cache = authenticate(username = username, password = password)
            if self.user_cache is None:
                #尝试用Email登录
                try:
                   User.objects.get(email = username).username
                except:
                    raise forms.ValidationError("请输入正确的用户名、密码")
                else:
                    username_from_email = User.objects.get(email = username).username
                    
                self.user_cache = authenticate(username = username_from_email, password = password)
                    
                #临时密码登录
                #user_temp_pwd_list = AccountTempPassword.objects.filter(temp_password = password, user__username = username)
                #if user_temp_pwd_list:
                #    user = user_temp_pwd_list[0].user
                    #login(self.request, user)
                #    self.request.session['temp_login'] = user
                    
                    #删除临时密码
                #    for user_temp_pwd in user_temp_pwd_list:
                #        user_temp_pwd.delete()
                        
                #    raise forms.ValidationError("")
                #else:
                
                
        self.check_for_test_cookie()
        return self.cleaned_data

class RegistrationForm(forms.Form):
    email = forms.EmailField()
    username = forms.RegexField(error_messages = {'required': u'用户名不能为空', 'min_length':u'至少是6个字符', 'max_length':u'最多是14个字符', 'invalid':u'用户名请以字母开头'}, regex = '^[a-zA-Z]\w*$', min_length = 6, max_length = 14)
    password = forms.CharField(widget=forms.PasswordInput, error_messages = {'required': u'密码不能为空', 'min_length':u'至少是6个字符', 'max_length':u'最多是16个字符'}, min_length = 6, max_length = 16)
    confirm_password = forms.CharField(widget=forms.PasswordInput, error_messages = {'required': u'确认密码不能为空', 'min_length':u'至少是6个字符', 'max_length':u'最多是16个字符'}, max_length = 16)
    
    def clean_email(self):
        email = self.cleaned_data['email']
        exists = User.objects.filter(email = email).count() > 0
        if exists:
            raise forms.ValidationError(u'邮箱已经被使用，请更换邮箱')
        return email
        
    def clean_username(self):
        username = self.cleaned_data['username']
        exists = User.objects.filter(username = username).count() > 0
        if exists:
            raise forms.ValidationError(u'该用户名已被使用，请重新输入')
#        if username[0].isdigit():
#            raise forms.ValidationError(u'用户名不能以数字开头')
        return username
    
    def clean(self):
        if ('confirm_password' in self.cleaned_data) and ('password' in self.cleaned_data):
            if (self.cleaned_data['confirm_password'] != self.cleaned_data['password']):
                self._errors["confirm_password"] = ErrorList([u'密码与确认密码不匹配'])
                del self.cleaned_data['password']
                del self.cleaned_data['confirm_password']
                
        return self.cleaned_data
    
class GetPasswordForm(forms.Form):
    email = forms.EmailField(max_length = 75, widget = forms.TextInput())
    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email = email).count() != 1:
            raise forms.ValidationError("这个邮箱不对应特定帐号!")
        return email

class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(error_messages = {'required': u'原始密码不能为空', 'min_length':u'至少是6个字符', 'max_length':u'最多是16个字符'}, min_length = 6, max_length = 16)
    new_password = forms.CharField(error_messages = {'required': u'新密码不能为空', 'min_length':u'至少是6个字符', 'max_length':u'最多是16个字符'}, min_length = 6, max_length = 16)
    confirm_password = forms.CharField(error_messages = {'required': u'新密码不能为空', 'min_length':u'至少是6个字符', 'max_length':u'最多是16个字符'}, required = False, max_length = 16)
    
    def __init__(self, request, data):
        if request:
            super(ChangePasswordForm, self).__init__(data)
        else:
            super(ChangePasswordForm, self).__init__()
        self.request = request
    
    def clean(self):
        if 'old_password' in self.cleaned_data:
            if not self.request.user.check_password(self.cleaned_data['old_password']):
                self._errors['old_password'] = ErrorList([u'原密码输入错误'])
                del self.cleaned_data['old_password']
        
        if ('confirm_password' in self.cleaned_data) and ('new_password' in self.cleaned_data):
            if (self.cleaned_data['confirm_password'] != self.cleaned_data['new_password']):
                self._errors["confirm_password"] = ErrorList([u'新密码与确认密码不匹配'])
                del self.cleaned_data['new_password']
                del self.cleaned_data['confirm_password']
                
        return self.cleaned_data

class ResetPasswordForm(forms.Form):
    password = forms.CharField(error_messages = {'required': u'新密码不能为空', 'min_length':u'至少是6个字符', 'max_length':u'最多是16个字符'}, min_length = 6, max_length = 16)
    confirm_password = forms.CharField(error_messages = {'required': u'确认密码不能为空', 'min_length':u'至少是6个字符', 'max_length':u'最多是16个字符'}, max_length = 16)
    
    def clean(self):
  
        if ('confirm_password' in self.cleaned_data) and ('password' in self.cleaned_data):
            if (self.cleaned_data['confirm_password'] != self.cleaned_data['password']):
                self._errors["confirm_password"] = ErrorList([u'新密码与确认密码不匹配'])
                del self.cleaned_data['password']
                del self.cleaned_data['confirm_password']
        return self.cleaned_data


class UserProfileForm(forms.Form):
    true_name = forms.CharField(required = False, error_messages = {'max_length':u'最多是14个字符'}, max_length = 14)
    intro = forms.CharField(required = False)
    location = forms.CharField(required = False)
    #phone = forms.RegexField(required = False, regex = '1\d{10}', error_messages = {'invalid':u'手机号码不规范'})
    email = forms.EmailField(max_length = 75, required = False, error_messages = {'max_length':u'邮箱地址不要超过75字符'})
    
    #def clean_phone(self):
    #   if self.cleaned_data['phone'] == '' :
    #        return None
    #    else :
    #       return str(self.cleaned_data['phone'])

works/forms.py
# -*- coding=utf-8 -*-

from django import forms
#from django.contrib.auth import authenticate, login
#from django.contrib.auth.forms import AuthenticationForm
#from django.contrib.auth.models import User
#from django.forms.util import ErrorList


class WorkForm(forms.Form):
    name = forms.CharField(error_messages = {'required': u'名称不能为空'}, max_length = 30)
    intro = forms.CharField(required = False)
    category = forms.CharField(required = False)
    isprivate = forms.IntegerField(required = False)
    
    def clean_isprivate(self):
        if 'isprivate' in self.cleaned_data:
            if self.cleaned_data['isprivate']:
                self.cleaned_data['isprivate'] = 1
            else:
                self.cleaned_data['isprivate'] = 0
            return self.cleaned_data['isprivate']

templates/accounts/list_user.html
{% extends "base.html" %}

{% block title %}{{title}}{% endblock %}

{% block content %}

<div class="container">
<ul class="nav nav-tabs">
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">排序方式 <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li {%if kind == 'all'%}class="active"{%endif%}><a href="?key=all&page={{users.number}}&cnt={{cnt}}{{get_extra}}">总排行</a></li>
                <li {%if kind == 'image'%}class="active"{%endif%}><a href="?key=image&page={{users.number}}&cnt={{cnt}}{{get_extra}}">画师</a></li>
                <li {%if kind == 'word'%}class="active"{%endif%}><a href="?key=word&page={{users.number}}&cnt={{cnt}}{{get_extra}}">写手</a></li>
                <li {%if kind == 'other'%}class="active"{%endif%}><a href="?key=other&page={{users.number}}&cnt={{cnt}}{{get_extra}}">围观</a></li>
            </ul>
    </li>
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">每页显示 <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li {%if cnt == 5%}class="active"{%endif%}><a href="?key=other&page={{users.number}}&cnt=5{{get_extra}}">5</a></li>
            <li {%if cnt == 10%}class="active"{%endif%}><a href="?key=other&page={{users.number}}&cnt=10{{get_extra}}">10</a></li>
            <li {%if cnt == 20%}class="active"{%endif%}><a href="?key=other&page={{users.number}}&cnt=20{{get_extra}}">20</a></li>
        </ul>
    </li>
</ul>

<table class="table table-striped">
  <thead>
    <tr>
        <th>排名</th>
        <th></th>
      <th>用户名</th>
      <th>画师</th>
      <th>写手</th>
      <th>围观</th>
    </tr>
  </thead>
  <tbody>
    {% for user in users.object_list %}
    <tr>
        <td width=34px><p>{{user.rank}}.</p></td>
        <td width=24px><a href="{%url profile user.username %}">
        <img src="/media/{{user.avatar}}" width="24px" height="24px" />
      </a></td>
      <td><a href="{%url profile user.username %}">
        {{user.username}}
      </a></td>
      <td><p>{{user.image}}</p></td>
      <td><p>{{user.word}}</p></td>
      <td><p>{{user.other}}</p></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<div class="pagination">
  <ul>
    {% if users.has_previous %}
    <li><a href="?key={{kind}}&page={{ users.previous_page_number }}&cnt={{cnt}}{{get_extra}}">上一页</a></li>
    {% endif %} 
    {% for i in paginator.page_range %}
    <li><a href="?key={{kind}}&page={{i}}&cnt={{cnt}}{{get_extra}}">{{i}}</a></li>
    {% endfor %}
    {% if users.has_next %}
    <li><a href="?key={{kind}}&page={{ users.next_page_number }}&cnt={{cnt}}{{get_extra}}">下一页</a></li>
    {% endif %}
  </ul>
</div>
</div>

{% endblock %}

{% block script %}
<script type="text/javascript" src="/static/js/bootstrap/bootstrap-dropdown.js"></script>
{% endblock %}

templates/accounts/login.html
{% extends "base.html"  %}

{% block content %}
<div class="container">
  <form action="" method="post">
    {% csrf_token %}
  {{form.as_p}}
  <button class="btn">登录</button>
  <a href="{%url reset_psw %}"><U>忘记密码？</U></a>
  </form>
</div>
{% endblock %}

templates/accounts/register.html
{% extends "base.html"  %}

{% block content %}
<div class="container">
  <form action="" method="post">
    {% csrf_token %}
  {{form.as_p}}
  <button class="btn">注册</button>
  </form>
</div>
{% endblock %}

templates/accounts/reset_psw.html
{% extends "base.html"  %}
{% block title %}重置密码{% endblock %}
{% block content %}
<form action="" method="post">
  {% csrf_token %}
{{form.as_p}}
<button class="btn">Reset</button>
</form>
{% endblock %}

templates/accounts/reset_psw_confirm.html
{% extends "base.html"  %}
{% block title %}重置密码{% endblock %}
{% block content %}
<form action="" method="post">
  {% csrf_token %}
{{form.as_p}}
<button class="btn">Reset</button>
</form>
{% endblock %}

templates/accounts/reset_psw_done.html
{% extends "base.html"  %}
{% block title %}重置密码{% endblock %}
{% block content %}
修改完成，<a href = "{% url login %}">点击登录</a>
{% endblock %}

templates/accounts/reset_psw_sended.html
{% extends "base.html"  %}
{% block title %}重置密码{% endblock %}
{% block content %}
邮件已发送，请查收。（有效期1hour）
{% endblock %}

templates/accounts/setting_notification.html
{% extends "accounts/settings.html"  %}
{% block title %}短信提醒{% endblock %}
{% block content_content %}
<div class="page-header">
    <h3>短信提醒</h3>
</div>
<table class="table table-striped table-condensed">
    <thead>
        <tr>
            <th>选择</th>
            <th>状态</th>
            <th>标题</th>
            <th>内容</th>
        </tr>
    </thead>
    <tbody>
        {% if notices %}
        {% for notice in notices %}
        <tr>
            <td><input type="checkbox" data-notifictaion-id="{{notice.id}}" /></td>
            <td>{%if notice.unseen %}<span class="label label-success">未读</span>{%else%}<span class="label">已读</span>{%endif%}</td>
            <td><a href="javascript:void(0)">{{notice.notice_type.display }}</a></td>
            <td class="notice_time">{{ notice.added|timesince }}前</td>
        </tr>
        <tr style="display:none;"><td colspan="4">{{notice.message|safe }}</td></tr>
        {% endfor %}
        {% else %}
        <tr><td colspan="4">暂时没有短信</td></tr>
        {% endif %}
        <tr>
            <td colspan="4"><!--button class="btn btn-error">删除</button--></td>
        </tr>
    </tbody>
</table>

<div class="modal hide fade in" id="alertModal">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>错误信息</h3>
  </div>
  <div class="modal-body">
    <p> </p>
  </div>
  <div class="modal-footer">
  </div>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="/static/js/bootstrap/bootstrap-modal.js"></script>
<script type="text/javascript" src="/static/js/jquery-ui-1.8.17.custom.min.js"></script>
<script>
$(document).ready(function(){
    //接受/拒绝
    $('div.invitation_action').find('a').click(function(e){
        var id = $(this).data('id'), 
            action = $(this).data('action'),
            direction = $(this).data('direction');
        $.ajax({type: 'get', url: '{%url ajax_user_invite_manage %}', data:{'id': id, 'action': action, 'direction':direction},
        	success: function(data){
		    	var data = JSON.parse(data);
		        if (data.state != 'done') {
					$('#alertModal .modal-body p').text(data.error);
          $('#alertModal .modal-footer a').attr("data-dismiss", "modal");
                $('#alertModal .modal-footer a').text("确定");
		            $('#alertModal').modal({'show': true});
				} else {
					$('#id_invitation_' + id).remove();
				}
		    },
		    error: function(jqXHR, textStatus){
		    	$('#alertModal .modal-body p').text('something wrong');
          $('#alertModal .modal-footer a').attr("data-dismiss", "modal");
                $('#alertModal .modal-footer a').text("确定");
                $('#alertModal').modal({'show': true});
		    }
        });
    });
    
    $('table tbody tr').find('td:eq(2)').on('click', function(){
        if ($(this).prev().text() == '未读'){
            var status = $(this).prev(),
                id = $(this).prev().prev().find('input').first().data('notifictaionId');
            $.ajax({type: 'POST', data:{'notice_id': id}, success: function(){
                status.html('<span class="label">已读</span>');
                }
            });
        };
       
       var content = $(this).parent().next();
       if (content.is(":visible")){
           $(this).parent().next().hide();
       }else{
           $(this).parent().next().show();
       }
   }) 
   {%for i in answered%}
   	$('#id_invitation_{{i}}').remove();
   {%endfor%}
});
</script>
{% endblock %}

templates/accounts/setting_profile.html
{% extends "accounts/settings.html"  %}
{% block title %}基础设置{% endblock %}
{% block content_content %}
<form class = "form-horizontal" ation="" method="post" enctype="multipart/form-data">
{% csrf_token %}
  <legend>基础设置</legend>
  <div class="row">
    <div class="span2">
      <img src="/media/{{profile.avatar}}" width="126px" height="126px" />
      <input class="input-file" id="id_avatar" name="avatar" type="file" style="width:126px;">
      <h3>{{profile.user}}</h3>
    </div>  
    <div class="span7">
      <div class="control-group">
        <label class="control-label" for="id_name">真实姓名</label>
        <div class="controls">
          <input class="span4" id="id_true_name" name="true_name" size="14" type="text" value="{{profile.true_name}}">
          <span  class="help-block">{{form.true_name.errors.0}}</span>
         </div>
       </div>
       <div class="control-group">
         <label class="control-label" for="id_name">地址</label>
         <div class="controls">
           <textarea class="span4" id="id_location" name="location" rows="2">{{profile.location}}</textarea>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="id_email">email</label>
          <div class="controls">
            <input class="span4 disabled" id="id_email" name="email" size="75" type="text" value="{{profile.user.email}}" disabled>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="id_name">自我介绍</label>
          <div class="controls">
            <textarea class="span4" id="id_intro" name="intro" rows="5">{{profile.intro}}</textarea>
          </div>
        </div>
      </div>
  </div>
  <div class="form-actions">
    <input type="submit" class="btn btn-success" value="保存">&nbsp;
  </div>
</form>
{% endblock %}

templates/accounts/setting_psw.html
{% extends "accounts/settings.html"  %}
{% block title %}修改密码{% endblock %}
{% block content_content %}
<form class = "form-horizontal" action="" method="post">
  {% csrf_token %}
{{form.as_p}}
<div class="form-actions">
	<input type="submit" class="btn btn-success" value="保存">&nbsp;
</div>
</form>
{% endblock %}

templates/accounts/setting_skill.html
{% extends "accounts/settings.html"  %}
{% block title %}基础设置{% endblock %}
{% block content_content %}
<div class="page-header">
	<h3>技能设置</h3>
</div>
<form class = "form-horizontal" ation="" method="post">
{% csrf_token %}
<div class="row"> 
	<div class="span2"> <p>
		你所掌握的技能在新岚会以图标的形式。。。。。
	</p> </div>
	<div class="span7">
		<div class="control-group">
			<div class="control">
				<ul class="inputs-list">
					{% for id, skill in skill_list.items %}
					<li> <label class="checkbox">
						<input type="checkbox" name = "skill_{{id}}" {{skill.1}}>
				        <span>{{skill.0}}</span>
					</label> </li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>
</div>
<div class="form-actions">
	<input type="submit" class="btn primary" value="Save changes">&nbsp;
</div>
</form>
{% endblock %}

templates/accounts/settings.html
{% extends "base.html"  %}

{% block content %}
<div class="container" style="width:700px;">
	<ul class="nav nav-pills">
	  <li class="{%if active == 'profile'%}active{%endif%}"><a href="../profile">基础设置</a></li>
	  <!--li class="{%if active == 'skill'%}active{%endif%}"><a href="../skill">技能设置</a></li-->
      <li class="{%if active == 'notification'%}active{%endif%}"><a href="../notification">阅读短信</a></li>
	  <li class="{%if active == 'psw'%}active{%endif%}"><a href="../psw">更改密码</a></li>
	</ul>
	<div class="content">
	{% block content_content %}{% endblock %}
	</div>
</div>
{% endblock %}