urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin

from notification import urls as notification

import settings
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'views.home', name='home'),
    url(r'^', include('tools.urls')),
    url(r'^', include('accounts.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^unread$', 'views.unread', name='unread'),
    url(r'^works/', include('works.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^notification/', include(notification)),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
)

works/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('works.views',
    url(r'^$', 'list_works', name='works'),
    url(r'^(?P<work_id>\d+)/$', 'show_work', name='show_work'),
    url(r'^rank/$', 'work_rank', name='work_rank'),
    url(r'^add/$', 'add_work', name='add_work'),
    url(r'^write_work/(?P<work_id>\d+)/$', 'write_work', name='write_work'),
    url(r'^edit_work/(?P<work_id>\d+)/$', 'edit_work', name='edit_work'),
    url(r'^show_element/(?P<element_id>\d+)/$', 'show_element', name='show_element'),
    url(r'^list_works_history/(?P<work_id>\d+)/$', 'list_works_history', name='list_works_history'),
)

accounts/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from easy_thumbnails.fields import ThumbnailerImageField
from notification import models as notification
from works.models import Work


class UserProfile(models.Model):
    user = models.ForeignKey(User, related_name='profile')
    avatar = ThumbnailerImageField(upload_to='avatar', default='avatar/default_avatar.jpg', resize_source=dict(size=(200, 250), crop='big'),)
    website = models.URLField(blank = True)
    intro = models.TextField()
    location = models.CharField(max_length = 50, blank = True)
    true_name = models.CharField(max_length = 14, blank = True)
    #email = models.EmailField()

class Visitor(models.Model):
    user = models.ForeignKey(User, related_name='visite')
    profile = models.ForeignKey(UserProfile, related_name='popularity')
    datetime = models.DateTimeField(auto_now_add = True)
    comment = models.CharField(max_length = 20, blank = True)

    class Meta:
        ordering = ['-datetime']
    
def create_user_profile(sender = None, instance = None, created = False, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
        Skill.objects.create(user=instance, skill='word')
        Skill.objects.create(user=instance, skill='image')
        Skill.objects.create(user=instance, skill='other')
        
models.signals.post_save.connect(create_user_profile, sender = User)

SKILL_CHOICES = (
    ('word', u'写手'),
    ('image', u'画师'),
#    ('design', u'设计美工'),
#    ('prog', u'程序员'),
#    ('music', u'音乐制作'),
#    ('onlook',u'围观'),
    ('other', u'其他'),
)
SKILL_CHOICES_MAP = {
    'word': u'写手',
    'image': u'画师',
    'other': u'其他',
}
class Skill(models.Model):
    user = models.ForeignKey(User, related_name='skills')
    skill = models.CharField(max_length=8, choices=SKILL_CHOICES)
    exp = models.IntegerField(default = 0)
    today_exp = models.IntegerField(default = 0)

class AccountTempPassword(models.Model):
    user = models.ForeignKey(User, related_name='tmp_psw')
    tmp_psw = models.CharField(max_length = 20)
    datetime = models.DateTimeField(auto_now_add = True)

class Invitation(models.Model):
    INVITE_CHOICES = (
        (u'noanswer', u'未响应'),
        (u'accept', u'已接受'),
        (u'reject', u'已拒绝')
    )
    work = models.ForeignKey(Work, related_name='invitation')
    invited = models.ForeignKey(User, related_name='invited')
    role = models.CharField(max_length=8, choices=SKILL_CHOICES)
    reason = models.CharField(max_length = 300)
    invite_status = models.CharField(max_length=8, choices=INVITE_CHOICES)
    notice = models.ForeignKey(notification.Notice, default=0)

works/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
#from synclee.club.models import Club, Project, Catalog
#from synclee.tab.models import SubTabClass, TabClass

from easy_thumbnails.fields import ThumbnailerImageField
from django.contrib.comments.moderation import CommentModerator, moderator

import os, settings

class TimeLine(models.Model):
    user = models.ForeignKey(User)
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    
    instance = generic.GenericForeignKey('content_type', 'object_id')
    created = models.DateTimeField(auto_now_add = True)

def get_image_path(instance, filename):
    return os.path.join('works', str(instance.id), filename)
class Work(models.Model):
    PRIVACY_CHOICES = (
        (u'Pub', u'公开'),
        (u'Fri', u'好友可见'),
        (u'Pri', u'私人'),
    )
    name = models.CharField(max_length=48)
    cover = ThumbnailerImageField(
        blank=True,
        upload_to=get_image_path,
        resize_source=dict(size=(360, 268), crop='smart'),
        default='no_cover.gif'
    )
    author = models.ForeignKey(User)
    category = models.CharField(max_length=16)
    created = models.DateTimeField(auto_now_add=True)
    isprivate = models.BooleanField(default=False)
    intro = models.TextField(blank=True)
    
    follower = models.ManyToManyField(User, related_name='follow')
    
    def __unicode__(self):
        return self.name
    
    def aver_score(self):
        return WorkScore.objects.filter(work=self).aggregate(average_score=models.Avg('score'))['average_score'] or 0
#def work_event(sender = None, instance = None, created = False, **kwargs):
#    if created:
#        TimeLines.objects.create(user = instance.author, event = instance)
#   
#models.signals.post_save.connect(work_event, sender = Work)
 
class Action(models.Model):
    ACTION_CHOICES = (
        ('support', u'支持'),
        ('follow', u'关注'), #TODO : Power by django-follow
        ('push', u'催稿')
    )
    user = models.ForeignKey(User)
    action = models.CharField(max_length=8, choices=ACTION_CHOICES)
    work = models.ForeignKey(Work)
    #push_today = models.IntegerField(default=0)

class Element(models.Model):
    CATEGORY_CHOICE = (
        ('text', u'文字'),
        ('image', u'图片'),
        ('line', u'分割线')
    )
    category = models.CharField(max_length=8, choices=CATEGORY_CHOICE)
    title = models.CharField(max_length=64, blank=True)
    content = models.TextField()
    work = models.ForeignKey(Work)

#TODO: 显示事件
#def element_event(sender = None, instance = None, created = False, **kwargs):
#    if created:
#        TimeLine.objects.create(user = instance.work.author, instance = instance)  
#models.signals.post_save.connect(element_event, sender = Element)

class WorkScore(models.Model):
    work = models.ForeignKey(Work)
    user = models.ForeignKey(User)
    score = models.PositiveSmallIntegerField(default = 0)

class WorkHistory(models.Model):
    work = models.ForeignKey(Work)
    user = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-date']

accounts/forms.py
#coding=utf-8

from django import forms
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.forms.util import ErrorList

#from apps.accounts.models import AccountTempPassword

class LoginForm(AuthenticationForm):
    username = forms.CharField(error_messages = {'required': u'用户名或邮箱不能为空'}, max_length = 30)
    password = forms.CharField(widget=forms.PasswordInput, error_messages = {'required': u'密码不能为空'})

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username and password:
            self.user_cache = authenticate(username = username, password = password)
            if self.user_cache is None:
                #尝试用Email登录
                try:
                   User.objects.get(email = username).username
                except:
                    raise forms.ValidationError("请输入正确的用户名、密码")
                else:
                    username_from_email = User.objects.get(email = username).username
                    
                self.user_cache = authenticate(username = username_from_email, password = password)
                    
                #临时密码登录
                #user_temp_pwd_list = AccountTempPassword.objects.filter(temp_password = password, user__username = username)
                #if user_temp_pwd_list:
                #    user = user_temp_pwd_list[0].user
                    #login(self.request, user)
                #    self.request.session['temp_login'] = user
                    
                    #删除临时密码
                #    for user_temp_pwd in user_temp_pwd_list:
                #        user_temp_pwd.delete()
                        
                #    raise forms.ValidationError("")
                #else:
                
                
        self.check_for_test_cookie()
        return self.cleaned_data

class RegistrationForm(forms.Form):
    email = forms.EmailField()
    username = forms.RegexField(error_messages = {'required': u'用户名不能为空', 'min_length':u'至少是6个字符', 'max_length':u'最多是14个字符', 'invalid':u'用户名请以字母开头'}, regex = '^[a-zA-Z]\w*$', min_length = 6, max_length = 14)
    password = forms.CharField(widget=forms.PasswordInput, error_messages = {'required': u'密码不能为空', 'min_length':u'至少是6个字符', 'max_length':u'最多是16个字符'}, min_length = 6, max_length = 16)
    confirm_password = forms.CharField(widget=forms.PasswordInput, error_messages = {'required': u'确认密码不能为空', 'min_length':u'至少是6个字符', 'max_length':u'最多是16个字符'}, max_length = 16)
    
    def clean_email(self):
        email = self.cleaned_data['email']
        exists = User.objects.filter(email = email).count() > 0
        if exists:
            raise forms.ValidationError(u'邮箱已经被使用，请更换邮箱')
        return email
        
    def clean_username(self):
        username = self.cleaned_data['username']
        exists = User.objects.filter(username = username).count() > 0
        if exists:
            raise forms.ValidationError(u'该用户名已被使用，请重新输入')
#        if username[0].isdigit():
#            raise forms.ValidationError(u'用户名不能以数字开头')
        return username
    
    def clean(self):
        if ('confirm_password' in self.cleaned_data) and ('password' in self.cleaned_data):
            if (self.cleaned_data['confirm_password'] != self.cleaned_data['password']):
                self._errors["confirm_password"] = ErrorList([u'密码与确认密码不匹配'])
                del self.cleaned_data['password']
                del self.cleaned_data['confirm_password']
                
        return self.cleaned_data
    
class GetPasswordForm(forms.Form):
    email = forms.EmailField(max_length = 75, widget = forms.TextInput())
    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email = email).count() != 1:
            raise forms.ValidationError("这个邮箱不对应特定帐号!")
        return email

class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(error_messages = {'required': u'原始密码不能为空', 'min_length':u'至少是6个字符', 'max_length':u'最多是16个字符'}, min_length = 6, max_length = 16)
    new_password = forms.CharField(error_messages = {'required': u'新密码不能为空', 'min_length':u'至少是6个字符', 'max_length':u'最多是16个字符'}, min_length = 6, max_length = 16)
    confirm_password = forms.CharField(error_messages = {'required': u'新密码不能为空', 'min_length':u'至少是6个字符', 'max_length':u'最多是16个字符'}, required = False, max_length = 16)
    
    def __init__(self, request, data):
        if request:
            super(ChangePasswordForm, self).__init__(data)
        else:
            super(ChangePasswordForm, self).__init__()
        self.request = request
    
    def clean(self):
        if 'old_password' in self.cleaned_data:
            if not self.request.user.check_password(self.cleaned_data['old_password']):
                self._errors['old_password'] = ErrorList([u'原密码输入错误'])
                del self.cleaned_data['old_password']
        
        if ('confirm_password' in self.cleaned_data) and ('new_password' in self.cleaned_data):
            if (self.cleaned_data['confirm_password'] != self.cleaned_data['new_password']):
                self._errors["confirm_password"] = ErrorList([u'新密码与确认密码不匹配'])
                del self.cleaned_data['new_password']
                del self.cleaned_data['confirm_password']
                
        return self.cleaned_data

class ResetPasswordForm(forms.Form):
    password = forms.CharField(error_messages = {'required': u'新密码不能为空', 'min_length':u'至少是6个字符', 'max_length':u'最多是16个字符'}, min_length = 6, max_length = 16)
    confirm_password = forms.CharField(error_messages = {'required': u'确认密码不能为空', 'min_length':u'至少是6个字符', 'max_length':u'最多是16个字符'}, max_length = 16)
    
    def clean(self):
  
        if ('confirm_password' in self.cleaned_data) and ('password' in self.cleaned_data):
            if (self.cleaned_data['confirm_password'] != self.cleaned_data['password']):
                self._errors["confirm_password"] = ErrorList([u'新密码与确认密码不匹配'])
                del self.cleaned_data['password']
                del self.cleaned_data['confirm_password']
        return self.cleaned_data


class UserProfileForm(forms.Form):
    true_name = forms.CharField(required = False, error_messages = {'max_length':u'最多是14个字符'}, max_length = 14)
    intro = forms.CharField(required = False)
    location = forms.CharField(required = False)
    #phone = forms.RegexField(required = False, regex = '1\d{10}', error_messages = {'invalid':u'手机号码不规范'})
    email = forms.EmailField(max_length = 75, required = False, error_messages = {'max_length':u'邮箱地址不要超过75字符'})
    
    #def clean_phone(self):
    #   if self.cleaned_data['phone'] == '' :
    #        return None
    #    else :
    #       return str(self.cleaned_data['phone'])

works/forms.py
# -*- coding=utf-8 -*-

from django import forms
#from django.contrib.auth import authenticate, login
#from django.contrib.auth.forms import AuthenticationForm
#from django.contrib.auth.models import User
#from django.forms.util import ErrorList


class WorkForm(forms.Form):
    name = forms.CharField(error_messages = {'required': u'名称不能为空'}, max_length = 30)
    intro = forms.CharField(required = False)
    category = forms.CharField(required = False)
    isprivate = forms.IntegerField(required = False)
    
    def clean_isprivate(self):
        if 'isprivate' in self.cleaned_data:
            if self.cleaned_data['isprivate']:
                self.cleaned_data['isprivate'] = 1
            else:
                self.cleaned_data['isprivate'] = 0
            return self.cleaned_data['isprivate']

templates/works/add_work.html
{% extends "base.html"%}

{% block title %}创建新作品{% endblock %}

{% block content %}
<div class="container">
    <div class="span7">
  <form class="form-horizontal" ation="" method="post"  enctype="multipart/form-data">
    {% csrf_token %}
      <legend>新增企划 - 填写基本信息 </legend>
      <div class="control-group">
        <label class="control-label" for="id_name">企划名称</label>
        <div class="controls">
          <input type="text" class="input-xlarge" id="id_name" name="name"> {{form.name.errors.0}}
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="id_isprivate">不公开</label>
        <div class="controls">
          <label class="checkbox">
            <input type="checkbox" id="id_isprivate" name="isprivate" value="1">
            勾选后其他用户不能查看该企划
          </label>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="id_category">分类</label>
        <div class="controls">
          <select id="id_category" name="category">
            <option value="other" selected="selected">其他</option>
            <option value="word">文字企划</option>
            <option value="image">图片企画</option>
          </select>
          <p class="help-block">选择后将排行榜中进入不同的分类，不会影响企划的制作</p>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="id_cover">企划封面</label>
        <div class="controls">
          <input class="input-file" id="id_cover" name="cover" type="file">
          <p class="help-block">选择并上传一张能代表这个企划的图</p>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="textarea">企划描述</label>
        <div class="controls">
          <textarea class="span4" id="id_intro" name="intro" rows="5"></textarea>
        </div>
      </div>
      <div class="form-actions">
        <button type="submit" class="btn btn-primary">保存，开始制作企划</button>
        <button type="reset" class="btn" onclick="window.history.go(-1)">返回</button>
      </div>
    </fieldset>
  </form>
    </div>

    <div class="span4">
        <blockquote>如果您恢复之前备份的企划，请点击导入
        <form class="form-horizontal" action="{%url import_work %}" method="post"  enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="work_zip"/><br/>
            <button type="submit" class="btn btn-primary">导入</button>
        </form>
        </blockquote>
    </div>
  
</div>
{% endblock %}


templates/works/list_works.html
{% extends "base.html" %}

{% block title %}所有企划{% endblock %}

{% block content %}

<div class="container">
<table class="table table-striped">
  <thead>
    <tr>
      <th>封面</th>
      <th>企划名称</th>
      <th>参与人</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for work in works.object_list %}
    <tr>
      <td width="170"><a href="{%url show_work work.id %}" class="thumbnail">
        <img src="/media/{{work.cover|default:'no_cover.gif'}}" alt="{{work.name}}" width="160" height="120">
      </a></td>
      <td width="470"><a href="{%url show_work work.id %}">{{work.name}}</a><p>{{work.intro}}</p></td>
      <td>
          <span class="label label-important">主创</span> &nbsp;<a href="{% url profile work.author.username%}">{{work.author.username}}</a><br/>
          {% for v in work.invitation.all %}
          {%if v.invite_status == 'accept'%}
          <span class="label label-success">{% if v.role == 'image'%}画师{%endif%}{% if v.role == 'other'%}围观{%endif%}</span> &nbsp;<a href="{% url profile v.invited.username%}">{{v.invited.username}}</a><br/>
          {%endif%}
          {% endfor %}
      </td>
      <td></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<div class="pagination">
  <ul>
    {% if works.has_previous %}
    <li><a href="?page={{ works.previous_page_number }}">上一页</a></li>
    {% endif %} 
    {% for i in paginator.page_range %}
    <li><a href="?page={{i}}">{{i}}</a></li>
    {% endfor %}
    {% if works.has_next %}
    <li><a href="?page={{ works.next_page_number }}">下一页</a></li>
    {% endif %}
  </ul>
</div>
</div>

{% endblock %}

templates/works/list_works_history.html
{% extends "base.html" %}

{% block title %}编辑历史{% endblock %}

{% block content %}

<div class="container">
<table class="table table-striped">
  <thead>
    <tr>
      <th>编辑者</th>
      <th>时间</th>
    </tr>
  </thead>
  <tbody>
    {% for i in history.object_list %}
    <tr>
      <td width="170"><a href = "{%url profile i.user.username%}">{{i.user.username}}</a></td>
      <td width="470">{{i.date|date:"j/n/Y H:i"}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<div class="pagination">
  <ul>
    {% if history.has_previous %}
    <li><a href="?page={{ history.previous_page_number }}">上一页</a></li>
    {% endif %} 
    {% for i in paginator.page_range %}
    <li><a href="?page={{i}}">{{i}}</a></li>
    {% endfor %}
    {% if history.has_next %}
    <li><a href="?page={{ history.next_page_number }}">下一页</a></li>
    {% endif %}
  </ul>
</div>
</div>

{% endblock %}

templates/works/show_element.html
{% extends "base.html"%}
{% load comments %}
{% block title %} {{element.title}} {% endblock %}

{% block content %}
<div class="container">
  {%if nav.prev %}
  <div class="row"><a href="{%url show_element element.id|add:"-1" %}"><button class="btn span6">上一个</button></a></div>
  {% endif %}
  <div class="row">
    <div class="span1"><span class="label label-success">{{ element.category }}</span></div>
    <h3 class="title">{{ element.title }}</h3>
    <div class="span10">
    {%  if element.category == "image" %}
      <p><img src="{{element.content}}" /></p>
    {% else %}
      <p>{{element.content|safe}}</p>
     {% endif %}
    </div>
  </div>
  
  {%if nav.next %}
  <div class="row"><a href="{%url show_element element.id|add:"1" %}"><button class="btn span6">下一个</button></a></div>
  {% endif %}
  
  
  {% get_comment_list for element as comment_list %}
  <div class="row"> <ul id="comment">
  {% for comment in comment_list %}
      <li>{{comment}}</li>
  {% endfor %}
  </ul> </div>
  
  {% get_comment_form for element as form %}
  <table>
    <form action="{% comment_form_target %}" method="post">
      {% csrf_token %}

      CONTENT: {{form.comment}}
      <tr>
        <td colspan="2">
          <input type="hidden" name="honeypot" id="id_honeypot">
          <input id="id_name" type="hidden" name="name" value="{{request.user.username|default:"游客"}}">
          <input type="hidden" name="email" id="id_email" value="{{request.user.email|default:"guest@doujinstg.cn"}}">
          {{form.timestamp}} {{form.content_type}} {{form.object_pk}} {{form.security_hash}} 
          <input type="submit" name="submit" value="Post">
        </td>
      </tr>
    </form>
  </table>
</div>
{% endblock %}

{% block script %}
<script>
$(document).ready(function(){
  $('.container form').onsubmit(function(){
    $.ajax({
      type : 'post',
      url : '/comments/post/',
      data : $(this).serialize(),
      success : $("#comment").append("<li>"+$("#id_name").val()+":"+$("#id_comment").val()+"</li>")
    })
    return false;
  })
  
  //console.log($('form').serialize());
})

</script>
{% endblock %}

templates/works/work_rank.html
{% extends "base.html" %}

{% block title %}企划排名{% endblock %}

{% block content %}

<div class="container">
<table class="table table-striped">
  <thead>
    <tr>
      <th>封面</th>
      <th>企划名称</th>
      <th>创建人</th>
      <th>分数</th>
    </tr>
  </thead>
  <tbody>
    {% for work in works.object_list %}
    <tr>
      <td width="170"><a href="{%url show_work work.id %}" class="thumbnail">
        <img src="/media/{{work.cover|default:'no_cover.gif'}}" alt="{{work.name}}" width="160" height="120">
      </a></td>
      <td width="470"><a href="{%url show_work work.id %}">{{work.name}}</a><p>{{work.intro}}</p></td>
      <td><span class="label label-important">主创</span> &nbsp;<a href="{% url profile work.author.username%}">{{work.author}}</a></td>
      <td><span class="label label-important">分数</span> &nbsp;{{work.aver_score}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<div class="pagination">
  <ul>
    {% if works.has_previous %}
    <li><a href="?page={{ works.previous_page_number }}">上一页</a></li>
    {% endif %} 
    {% for i in paginator.page_range %}
    <li><a href="?page={{i}}">{{i}}</a></li>
    {% endfor %}
    {% if works.has_next %}
    <li><a href="?page={{ works.next_page_number }}">下一页</a></li>
    {% endif %}
  </ul>
</div>
</div>

{% endblock %}